### ISSUE TITLE
Event Dots above Day in Android 7

### ISSUE THREAD

**Issue by OliverMannhart** [SundeepK/CompactCalendarView#104]
Sometimes it shows the dot above the day.
See:
[Example View](https://drive.google.com/file/d/0B1RaWmOtsSQVbHc3UWJOaTVyN2s/view?usp=sharing)

This behaviour does not always occur. And I was only able to reproduce it on a Nexus 6P with Android 7.0.

I use compact-calendar-view:1.9.0

Thanks for your support

**Comment by SundeepK** [comment]
Interesting, maybe it's something with Android 7.0 and high res screens? What other phones did you try with?

Thank fully I have nexus 6p, I'll update to Android 7 and try it out. Did you follow some specific steps to produce this result?

**Comment by OliverMannhart** [comment]
I did test it on a Samsung Galaxy S7 and some devices with low res screens. 
I could not reproduce it there. 
I also think it could be something with Android 7.0. 
On Monday I should get another Android 7.0 device. I will test it there as well.

**Comment by SundeepK** [comment]
Thanks, I'll try and do some investigating. After a brief look, when I tried it using nexus 6p emulator, it worked correctly. When I tried on a nexus 6p phone with version 7.0 installed, I saw problems.

However, I think I may have a possible one line fix to the problem, call the following in the internal calendar:
`eventsCalendar.setMinimalDaysInFirstWeek(1);`

Basically, if you do:

Pre 7.0 android:

```java
 Calendar calendar = Calendar.getInstance();
 Log.d("Calendar_tag", "getMinimalDaysInFirstWeek " + calendar.getMinimalDaysInFirstWeek());

```

You will see `getMinimalDaysInFirstWeek 1` print out.

If you repeat this on a android 7.0, you will see 4. 

I think the default is dependent on particular versions it seems. I tried it on Java 8 not running on android and saw 4 also. This is whats causing the problem I believe, because setting it 1 fixes the problem. 

This is required because I use the `eventsCalendar.get(Calendar.DAY_OF_MONTH);` call to get the current week of the current month for drawing events. 

Looks like this is specific to Android 7.0, thanks for raising this issue.

**Comment by SundeepK** [comment]
I have released a beta for testing. Please give this version a try with both pre 7.0 and android 7.0:

```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.1-beta-1.0'
}
```

I have tested using an emulator and it seems ok, also tested with android 7.0 and the bug seems to be fixed.

**Comment by OliverMannhart** [comment]
Hey there,

Thanks for the beta. I tested it on Android 7.0 and older devices and your fix does work. 

I also tested on a Nexus 5X before Android 7.0 and after the update. And it did behave exactly as you described.

I think you can close the issue.

Thanks a lot.

**Comment by SundeepK** [comment]
Thanks for verifying this fix. I will release a new version soon, when I get time either today or tomorrow.

**Comment by SundeepK** [comment]
Available in:
```gradle

dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.1'
}

```
