### ISSUE TITLE
Refresh View after Async-task operation

### ISSUE THREAD

**Issue by XxGoliathusxX** [SundeepK/CompactCalendarView#106]
How to refresh calendarview the best way after setting up the event-indicators in async-task?

**Comment by SundeepK** [comment]
The best way is to collect all events in a seperate thread (runnable or asynctask, what ever works for you) to a list and then add them in one go:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarView.java#L190

It's the most efficient approach because you only draw the calendar once. You can load your events in batchs for multiple network calls, but each time you load them, make sure to use that method.

You can also call `invalidate()` to redraw the calendar if you need to.

**Comment by XxGoliathusxX** [comment]
Because when I monthscroll and then add an item to that day async and want to remove it after that again, i get an error that it does not exist.

**Comment by XxGoliathusxX** [comment]
When I do it in the UI-Thread this error does not appear

**Comment by SundeepK** [comment]
Can you share the error you are seeing? Also, make sure any update are made in the UI thread. Do not update in any other thread than the main UI thread. So you can load events in a seperate thread, but always update the calendar events in the UI thread.

**Comment by XxGoliathusxX** [comment]
I dont thing my code will help you because it contains a huge amount of code that is very complex

**Comment by SundeepK** [comment]
What method are you using to query for events? As I mentioned before, you must use UI thread when interacting with the view since it's not thread safe. It's possible you may be adding events in different threads and querying in others?

**Comment by XxGoliathusxX** [comment]
Yes. Then AsyncTask seems not to work with this library.

**Comment by XxGoliathusxX** [comment]
Ok It works now. I changed the following. Getting all Events from the Database and collect them in a list I do in doInBackground(). Then in postExecute I add this list via compactCalendarView.addEvents() .

**Comment by SundeepK** [comment]
Thanks, that it what I expect for loading from database. Closing as this issue.
