### ISSUE TITLE
How to show current month; event dot appearing on delay

### ISSUE THREAD

**Issue by fermatijoe** [SundeepK/CompactCalendarView#113]
Hello I have two questions:

First, I would like to display the current month's name inside the calendar. Right now you can scroll between months but there is no idicator of what month you are actually seeing. I looked in the source but could not find any method to retrieve current visible month. Also how do I change the week days' abbreviations in uperrcase? Right now is showing l,m,m,g,v,s,d which are the week days in my locale. I want them to be L,M,M,G,V,S,D in uppercase.

[Screen](http://i.imgur.com/Isgl6zq.png)

Second, I noticed that if I add a new event the dot under the day number does not appear until i click again the calendar (in any place). This is frustrating since one might not know that he actually added the event.Code I use to add the event:

```
new DialogInterface.OnClickListener()
            {
                public void onClick(DialogInterface dialog, int id)
                {
                    List<Event> events = compactCalendarView.getEvents(dateClicked.getTime());
                    if(events.size() == 0){
                        Event ev1 = new Event(Color.GREEN
                                , dateClicked.getTime()
                                , "completed_true");
                        compactCalendarView.addEvent(ev1, true);
                    }
                }
            });
```

Thank you in advance.

**Comment by fermatijoe** [comment]
PS: is tehre a way to get all the events in the month without iterating every day? I want to save the events in a database so that they persist in different app launches.

**Comment by XxGoliathusxX** [comment]
For the first you need a textview placed somewhere. Then you get the currentselectedmonth and use a simpledateformatter to format the date

**Comment by SundeepK** [comment]
Hi @fermatijoe as mentioned in order to display the current month you will need to add a text view and display the current month. The view is generic and so allows you to set the current month on what ever format you want or even in the toolbar, as shown in the sample app. Have a look at the sample to get an idea. I'm more than happy to answer any question for that.

To get all the events for the current month call `getEventsForMonth(long epochMillis)` just pass it the epoch from the date object or where ever you are loading the date from.

Calling ` compactCalendarView.addEvent(ev1, true);` however should redraw the the calendar for you. So I'm not sure why its not redrawing the calendar. Perhaps because there's some weirdness with the onCallback from the DialogInterface? I've changed the sample app to add a new event on a button click and it redraws immediately. I'll try with DialogInterface when I have a chance to see if there is some problem there. You can also call `compactCalendarView.invalidate();` this will also redraw the calendar for you. So add the event and then invalidate the view and see if that fixes the problem.

Regarding the weekdays, can you show me the local setting you are setting on the calendar? Or is the local unchanged and this is shown by default. If so can I know your locale? Internally, this method is called to get the weekdays:

https://developer.android.com/reference/java/text/DateFormatSymbols.html#getShortWeekdays()

And then the first letter is taken. By default is seems that English days are capitalised but maybe other locales are not? This means we'll need to capitalise the first letter or use some date formatter. So this seems like an enhancement to me.

**Comment by fermatijoe** [comment]
Hi thanks for the reply, I'm working through implementing the month textview now. I have set up the view but I can't find the specific method to get the currently selected month. Thanks.

**Comment by SundeepK** [comment]
You can call `compactCalendarView.getFirstDayOfCurrentMonth()` to get the first day of the month. Then you can format is how you like, e.g:

```java
  SimpleDateFormat dateFormatForMonth = new SimpleDateFormat("MMM - yyyy", Locale.getDefault());
```

You will also need to register a listener using `compactCalendarView.setListener()` then when ever a month is scrolled you can update the text view with the date. Here's an example:

```java

        compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                // other code here
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                currentMonthTextView.setTitle(dateFormatForMonth.format(firstDayOfNewMonth));
            }
        });
```

**Comment by fermatijoe** [comment]
Thank you very much, I got it working.
Regarding the redraw issue I can't find a solution. I noticed that the event dot doesn't appear until I click another day in the calendar, not just inside the view but I must click a day. Could it be because I have the calendar inside a CardView? I would upload the code on github but android studio is giving me errors.

As for the locale I have not changed it in code, I guess it is adapting to the locale of my phone (it-IT). I'll get back to you once I manage to save the events in the database. Thanks again.

**Comment by SundeepK** [comment]
@fermatijoe Interesting, I havn't tried it inside a CardView but I don't see any reason why it should not work. Did you try calling `invalidate` method on the calendar once you add an event?

**Comment by fermatijoe** [comment]
Yes I did that. Also sorry to trouble you again but I am not bale to get all events in the month. I can only see some of them: below is the code

Basically I have different _mTask_ objects which should have different events on different calendar views. But If I add a single event to a single calendar view from the logs I see that more than one event is saved in the database (its the just added event + the following events I already added in previous app sessions).

In DetailActivity onCreate (yes i switched to using activities instead of fragments):

    //TODO populate calendar with events from database for THIS task
        List<CalendarEvent> events = DatabaseUtils.getAllSavedEvents(mTaskId);
        Log.v(LOG_TAG, "Retrieved events: " + events);
        for(CalendarEvent e : events){
            Event ev1 = new Event(e.getColor()
                    , e.getTimeInMillis()
                    , e.getData());
            compactCalendarView.addEvent(ev1, true);
        }

The method in DatabaseUtils 

    public static List<CalendarEvent> getAllSavedEvents(String taskId){

        return Select.from(CalendarEvent.class)
                .where(Condition.prop("id")
                        .eq(Integer.valueOf(taskId)
                                .toString()))
                .list();

    }


Where CalendarEvent is an exact copy of your Event class. _mTaskId_ or _taskId_ is the auto incrementing id value in the database.
Here is the log where for example only 1 event is retrieved when It should retrieve 2 of them.

    D/SQL Log: SQLiteQuery: SELECT * FROM CALENDAR_EVENT WHERE (id = ? )

    V/DetailActivity: Retrieved events: [Event{color=-16711936, timeInMillis=1476482400000, data=completed_true}]



Lastly here is how I save an event: first I create a calendar event to show it, then I create a copy event and store it in the database

    Event ev1 = new Event(Color.GREEN
                                    , dateClicked.getTime()
                                    , "completed_true");
                            compactCalendarView.addEvent(ev1, true);
                            compactCalendarView.invalidate();

                            //recreate event in order to save with database
                            CalendarEvent ev11 = new CalendarEvent(Color.GREEN
                                    , dateClicked.getTime()
                                    , "completed_true"
                                    , mTaskId);
                            ev11.save();

This is driving me mad. Thanks.

**Comment by SundeepK** [comment]
@fermatijoe I would suggest a few pointers:

If you want to add multiple events. Create an `List<Event> events`. Store all the event in the list and then call `compactCalendarView.addEvents(events)` this far more efficient than adding multiple single events. 

I'm not sure I properly understand the problem. Are you saying that you added more than one event to your database but you only got back 1? Are you sure you are not replacing events in your database because your referencing the same taskId? Is the taskId always uniqe. Can you prove that is the case but manually adding events and querying your database with a select all? 

Remember you can store any object as the data for the `compactCalendarView` `Event` object. So you can create an object which will hold both the`taskId` and the `completed_true` status. This might be handy in debugging so you know that `compactCalendarView` is storing your unique objects correctly.

**Comment by SundeepK** [comment]
If there is any further update to this issue, please re-open.
