### ISSUE TITLE
Some tests are not passing on 31st on some months

### ISSUE THREAD

**Issue by JulienArzul** [SundeepK/CompactCalendarView#116]
Hello,

Three tests do not pass when launched on the 31st day of the month (for example 31st of august).

The three tests in question are : 
- testItDrawsEventDaysOnCalendar
- testItDrawsMultipleEventDaysOnCalendar
- testItDrawsMultipleEventDaysOnCalendarWithPlusIndicator

Here is the error returned : 
`com.github.sundeepk.compactcalendarview.CompactCalendarControllerTest > testItDrawsEventDaysOnCalendar FAILED`
`    org.mockito.exceptions.verification.TooManyActualInvocations at CompactCalendarControllerTest.java:305`

`com.github.sundeepk.compactcalendarview.CompactCalendarControllerTest > testItDrawsMultipleEventDaysOnCalendar FAILED`
`    org.mockito.exceptions.verification.TooManyActualInvocations at CompactCalendarControllerTest.java:321`

`com.github.sundeepk.compactcalendarview.CompactCalendarControllerTest > testItDrawsMultipleEventDaysOnCalendarWithPlusIndicator FAILED`
`    org.mockito.exceptions.verification.TooManyActualInvocations at CompactCalendarControllerTest.java:337`

They probably don't work in February as well.

I haven't really looked at why yet.

**Comment by SundeepK** [comment]
Hi these will fail if you have changed the code which draws days. The idea behind the test is, for example `testItDrawsEventDaysOnCalendar`, is that if there is one event on each day of the month then I expect it to draw a circle 29 times (minus 1 because the current day is ignored). All these tests will work on a similar idea. It could be these tests are too fine grained but it keeps confidence to know that its not drawing more than it needs to.

Let me know if you have any questions.

**Comment by JulienArzul** [comment]
I don't think it's a problem from modifications I made : the tests pass every day except on the 31st.

From your explanation (and a look at the code in question), I 'm guessing it's because if we are the 31st, the current day won't be one of the day where there is an event thus the draw will be called 30 times instead of 29.
It probably won't work in February as well since there is only 28 (or 29) days in the month : draw will be called only 27 (or 28) times.

You'll probably have to add different conditions depending on the current day in the test... The real problem is that the tested method depends on an internal calendar that you can't mock easily.

**Comment by SundeepK** [comment]
@JulienArzul Yes your right, it's set to work only on specificdate because like you mentioned it can be little awkard to mock system time. Thats why the test, e.g. testItDrawsEventDaysOnCalendar, is set to use date for June which has 30 days. It will not work for the months you mentioned. But thats ok though right, because we explicity set the month we are testing. If you want to test for month that have 31 days then we can just add another test case.

However, If you want to mock systemtime, then I suggest we can mock system date/time using http://joda-time.sourceforge.net/apidocs/org/joda/time/DateTimeUtils.html. We can simply add JodaTime as a test dependency and it should be robust then. Which might be a good idea.

**Comment by JulienArzul** [comment]
Actually, after looking a bit more at the code, I think that we've found a bug : since we're setting the month to draw to June 2015, we should never have the current day selected in this month ! And the events should actually be drawn 30 times.

The bug is with the variable `isCurrentSelectedDay` : the check is only whether the day of the month is the same than the day of the selected date. It doesn't take the month into account.

I think that right now it shouldn't happen since you automatically select the first day of the month when switching month. So we have two choices : 
- change the test to select the first day of june before drawing the events
- correct the method to check the month of the selected date so that future enhancements like not changing the selected day when changing the month (I've seen issues regarding that) are handled

The second solution is better in my opinion : it handles both case elegantly. If you want me to do it, don't hesitate, I'll probably have some time tomorrow.

**Comment by JulienArzul** [comment]
I've proposed a correction in a Pull Request

**Comment by SundeepK** [comment]
👍  @JulienArzul I havn't had a chance to look at the pull request, will do when I get time.

**Comment by SundeepK** [comment]
Merged pull request, closing this issue now.
