### ISSUE TITLE
Can not make the Calendar appears pressing a button

### ISSUE THREAD

**Issue by JonnyCiel** [SundeepK/CompactCalendarView#138]
Hello, thanks for your help in advance.

I would like to know if there is a known bug about this situation. Because i can hide the calendar either with hideCalendarWithAnimation or just HideCalendar.

But when i try to show the Calendar, any of the two methods we have are not  working at all. It just nothing happens, and i even just copy the code from the example and is not working either.

I am using the library version " compile 'com.github.sundeepk:compact-calendar-view:1.9.5'" and my button is a FloatingActionButton.

Thanks.

**Comment by SundeepK** [comment]
Hi @JonnyCiel can you show me your layout xml? Do you have the `compactCalendarTargetHeight` set in the xml? 
https://github.com/SundeepK/CompactCalendarView/blob/master/sample/src/main/res/layout/main_tab.xml#L14

I think this is not documented in the readme, but will add it. It's in the sample app though. Thing is we can't reliable find out the height the calendar shoule be, without being told before hand. So set that value to the height you intend the calendar to be. 

Actually, we can replace by directly getting `layout_height` instead of having another attribute for it in the xml, which is something that was overlooked when I did it initailly. I'll add this as an enchancement todo.

**Comment by JonnyCiel** [comment]
Hello, sir, thanks for your response.

This is my xml layout.

> <com.github.sundeepk.compactcalendarview.CompactCalendarView
                android:id="@+id/ambientesActivityCalendar"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="250dp"
                app:compactCalendarBackgroundColor="@color/colorPrimaryDark"
                app:compactCalendarCurrentDayBackgroundColor="@color/colorPrimary"
                app:compactCalendarCurrentDayIndicatorStyle="fill_large_indicator"
                app:compactCalendarCurrentSelectedDayBackgroundColor="@color/colorAccent"
                app:compactCalendarEventIndicatorStyle="small_indicator"
                app:compactCalendarOtherMonthDaysTextColor="#534c4c"
                app:compactCalendarTargetHeight="250dp"
                app:compactCalendarTextColor="#fff"
                app:compactCalendarTextSize="12sp"
                />

Thanks for your help. Because i really want to offer the user the posibility to hide the calendar, since the animation is very very nice.

**Comment by JonnyCiel** [comment]
I already fix this issue. Thanks for your answer :)
