### ISSUE TITLE
How to set only one dot instead of three dots for multiple event in the same day?

### ISSUE THREAD

**Issue by JaydipRadadiya** [SundeepK/CompactCalendarView#154]
I want to only one dot for more than one  event in same date. How can I do this or is there any solution available already? I am using v1.9.5
Please let me know.

Thanks!

**Comment by SundeepK** [comment]
The only way todo this currently is to just create one event and maintain some data structure on your end to know when to create another event or not. Alternativly, you can fork the code, import to your project and delete the code which draws multiple dots. Which should be simple todo (I can help you if you need). I also recomend to use the latest version because of bug fixes and new features (v1.9.7).

**Comment by JaydipRadadiya** [comment]
Appreciate for your response!
I don't find out where to draws multiple dots. Can you help me?
Thank you for your suggestion.

**Comment by SundeepK** [comment]
Should be simple todo. Have a look at this line:
https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L751

Change:
```java
    if (eventsList.size() >= 3) {
        drawEventsWithPlus(canvas, xPosition, yPosition, eventsList);
    } else if (eventsList.size() == 2) {
        drawTwoEvents(canvas, xPosition, yPosition, eventsList);
    } else if (eventsList.size() == 1) {
         drawSingleEvent(canvas, xPosition, yPosition, eventsList);
    }
```

to 
```java
    drawSingleEvent(canvas, xPosition, yPosition, eventsList);
```
This should just draw one event with the color from the fist event.

**Comment by JaydipRadadiya** [comment]
Wow Thats it!  Works like charm.

**Comment by leonardosetiadi** [comment]
how can i modify the compactcalendarcontroller.java ?
