### ISSUE TITLE
How to start showCalendarWithAnimation(); when list view is empty ?

### ISSUE THREAD

**Issue by QArtur99** [SundeepK/CompactCalendarView#157]
Hi @SundeepK ,
I'd like to set onTouch event under Calendar View to hide and show Calendar. If in ListView are some events it is working well but when list is empty  calendar can hide but it cant show again.
What should I do for show calendar again by touch event when list is empty?

**Comment by SundeepK** [comment]
@QArtur99 I think the better design is to have the button on the toolbar with the date/month on it. When you click that button you can show the calendar. This way you can always show the calendar regardless of is you have any listview items. This is how Google calendar works and many apps I have seen and its simple todo because its just a button.

**Comment by SundeepK** [comment]
Check issue #39 for a demo gif in the comments which is exactly what I mean.

**Comment by QArtur99** [comment]
Thank you I set height for empty listview its enough for correct work of touch event.
