### ISSUE TITLE
First day selected after nextMonth()

### ISSUE THREAD

**Issue by lucasrafagnin** [SundeepK/CompactCalendarView#167]
Even with the compactCalendarShouldSelectFirstDayOfMonthOnScroll = true option, after call nextMonth() method, the next month comes with the first selected day.

Is a bug?

**Comment by SundeepK** [comment]
Set `compactCalendarShouldSelectFirstDayOfMonthOnScroll = false` to disable first day from being selected.

That being said, I think it was a mistake in the comment you made because it looks like a legit bug:
https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L326

There should be a simple if check to see if `shouldSelectFirstDayOfMonthOnScroll` is false in both `showNextMonth` and `showPreviousMonth` and don't set the `currentDate`. I think I can fix this issue sometime tomorrow. I will also add a unit test case for this also to make sure it's not missed in the future.

Thanks for raising the issue!

**Comment by lucasrafagnin** [comment]
Nice!

sorry for my English :D

**Comment by SundeepK** [comment]
Just an update, I think I fixed the bug and committed to a branch. Looks like I won't have enough time today to finish it, but will hopefully get around doing the unit test and release tomorrow or day after.

**Comment by SundeepK** [comment]
Should be in version, please allow for some time for it to be available.
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:2.0.0'
}
```
