### ISSUE TITLE
I want to hide the days name i.e. S M T W T F S

### ISSUE THREAD

**Issue by dheerajjaiswal08** [SundeepK/CompactCalendarView#229]
Please help me

**Comment by SundeepK** [comment]
There's no native way to remove the header there, but you can call `setDayColumnNames()` with an array of empty strings. Basically that method allows you to set custom day names, so instead of S M T W T F S, you can try passing in 7 empty strings. If that doesn't work for you then you will have to import the library and makes some changes. Let me know if you need some help with that case.

**Comment by dheerajjaiswal08** [comment]
Thank You Very Much Sir.

Sir one more think I want to know that

how to make calendar view in vertical scrolling?
Is there any method to achieve this?

If no, Sir Please provide me code to do this.

Once again Thank you very much sir.

**Comment by SundeepK** [comment]
It is possible, but it would require quite a large rewrite. Currently, the library only handles horizontal scrolling. To handle vertical, you need re-write the onTouch and scrolling code in the `CompactCalendarController` class and re-draw things using y value instead of x.
