### ISSUE TITLE
Change background of date field on click

### ISSUE THREAD

**Issue by GabiR** [SundeepK/CompactCalendarView#3]
When clicking on a day it should have a different background to see the selected day.

**Comment by grobarko** [comment]
Yes, selected day is a necessity.

**Comment by SundeepK** [comment]
Umm interesting, I never noticed this but I made a mistake when naming a method. setMonth actually sets the current day rather than the month. So, as a work around, on a day click you can use setMonth but just pass the currentdate. This will redraw the calendar and highlight the day for you.

I'll put in a fix to set the day automatically when a day is selected and fix that method name to be something like, "setDay" and add a method to set the month as well. Thanks for pointing this one out.

**Comment by GabiR** [comment]
Ok, it is loading pretty slow when redrawing the calendar with setMonth() so it isn't the best solution.

**Comment by SundeepK** [comment]
Yeah, this is a temporary work around to get the functionality working until I fix the bug. Actually, it will redraw all three calendars (previous month, current month and next month). Ideally, selecting a day should draw only the current month which should improve any performance problems. 

Alternatively, remove the background for the previous day that was selected and draw a new one where the current one is. This will require more code changes but probably be the best way to do it.

**Comment by GabiR** [comment]
When do you estimate that the bug will be fixed? :smile:

**Comment by SundeepK** [comment]
I'll try squeeze the change in the next few days if I can, but I can be busy because of work and what not.

**Comment by SundeepK** [comment]
I think the actual slowness was caused by the listener being called too early. This is because the listener would be called before the actual calendar was redrawn. So, if the code in clients implementation of the ``` CompactCalendarViewListener ``` did alot of processing, then it would delay the calendar from being drawn. This probably made it seem like it was slow in drawing. So I re-factored things slightly, so that the calendar would be drawn first and then the listener for a day click is called, which seems more correct.

**Comment by SundeepK** [comment]
Note, ``` setMonth ``` has been replace by ``` setCurrentDate ``` since it actually describes what its doing better.
