### ISSUE TITLE
remove all events at once in calendar with no events

### ISSUE THREAD

**Issue by kprathap23** [SundeepK/CompactCalendarView#40]
is there any way to remove events (dots under date ) all at once rather than using 
below removeEvent method

compactCalendarView.removeEvent(new CalendarDayEvent(dateClicked.getTime(), Color.argb(255, 169, 68, 65)), true);
adapter.notifyDataSetChanged();

**Comment by SundeepK** [comment]
have a look at ``` public void removeEvents(List<CalendarDayEvent> events) ```

**Comment by SundeepK** [comment]
Sorry mis-interreptted that. Do you mean something like ```removeAllEvents()```?

**Comment by kprathap23** [comment]
Yes . removeAllEvents()

**Comment by SundeepK** [comment]
That we be a feature request, should be quite easy todo.

**Comment by kprathap23** [comment]
This is such a good Library so far i have seen for Calendar control .any plans to integrate day View, week view in near future to this library.

**Comment by SundeepK** [comment]
You might be interested in my other library https://github.com/SundeepK/MultiDayCalendarView. It provides a 3 day calendar view, but It is not fully finished yet, that's why it's not on maven. But it is in a usable state (I use it in my own projects), just not finished. It looks like the Google Calendar as well. I'm planning on adding some further animations to make it look nicer, that why it's not finished.

**Comment by kprathap23** [comment]
Thank u . I will try this Library.

**Comment by SundeepK** [comment]
Will release new version in the next day or so.

**Comment by SundeepK** [comment]
Available in version:

``` 
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.0'
}
```

**Comment by kprathap23** [comment]
Thank you..
