### ISSUE TITLE
i want previous and next month date showing in current month

### ISSUE THREAD

**Issue by Debdeep1234** [SundeepK/CompactCalendarView#46]
How do i show previous and next month date also in current month...when i click on dissable month date is showing in toast bt it is not visible in your code....how do i visible those previous and next month date...please reply me...

**Comment by SundeepK** [comment]
Hi, I'm not sure I understand the question. Can you explain with a little more detail what exactly you need? Maybe add some sample code?

**Comment by Debdeep1234** [comment]
![screenshot_2015-12-11-20-53-02 1](https://cloud.githubusercontent.com/assets/16251130/11747447/46f01a88-a049-11e5-8f48-89e5989573f6.png)
![screenshot_2015-12-11-20-53-20 1](https://cloud.githubusercontent.com/assets/16251130/11747473/69439fec-a049-11e5-9e32-983d20f377a6.png)


Please see the uploaded screenshot....and please help me

**Comment by SundeepK** [comment]
Ok well you havn't *explained* what you want. But from what I can see is you want to have scrolling with buttons and not with finger touch. Have a look at the sample that comes with the library. Basically, you need to disable scrolling:

``` compactCalendarView.shouldScrollMonth(false); ```

Then you want to create 2 buttons for scrolling previous month and next month:

```
        showPreviousMonthBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                compactCalendarView.showPreviousMonth();
            }
        });

        showNextMonthBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                compactCalendarView.showCalendarWithAnimation();

                // compactCalendarView.showNextMonth();
            }
        });
```

This is all in the sample app, so have a look.

**Comment by kppf** [comment]
The Enhancement needed by the @Debdeep1234 is that the next and previous month's dates are shown in current month Calendar. 

E.g. Month starts on Wednesday
So in the first row, Monday and Tuesday are currently blank - he wants to show 30 and 31 there.

E.g. Month ends on Thursday.
Then show next month's 1 2 3 on Friday Saturday Sunday instead of leaving that space blank.

Check the circled/oval-ed numbers in attached image

![69439fec-a049-11e5-9e32-983d20f377a6](https://cloud.githubusercontent.com/assets/3091173/11760990/811ae542-a0d7-11e5-8f37-fa911762b870.png)

**Comment by SundeepK** [comment]
Thanks @kppf for making that more clear.

**Comment by Debdeep1234** [comment]
please any one help me

**Comment by SundeepK** [comment]
This has now been merged. Will update with a new version once its released.
