### ISSUE TITLE
First day of the month always selected..

### ISSUE THREAD

**Issue by spartacusrex99** [SundeepK/CompactCalendarView#64]
Thanks for this code. Wonderful.

The First day of the month is always selected. When you scroll through the months. It's in the drawMonth code of CompactCalendarController. Before I hack it to work, I was wondering if this is intentional ?

**Comment by SundeepK** [comment]
Hi thanks for raising the issue, there is already a pull request open for this: #55. I need to merge another branch before I proceed with merging. I will try to make some time todo so soon.

I will close this issue, since it's pretty much what the pull request is trying to fix. I can't give you a time limit on when it will be done unfortunatly.
