### ISSUE TITLE
Using buttons instead of horizontal scrolling

### ISSUE THREAD

**Issue by javo0112** [SundeepK/CompactCalendarView#8]
Hi SundeepK

I am using the widget in a layout with tabs and the viewpager and of course the horizontal scrolling gesture is already in use by the viewpager so i want to put a pair of buttons next month and previous month.

![device-2015-08-03-183011](https://cloud.githubusercontent.com/assets/6923752/9050003/6b05732e-3a0e-11e5-96d4-4214c106f118.png)

I've been reading the source but i'll really appreciate if you could point me in the right direction to achieve this.

Thanks for the calendar.

**Comment by SundeepK** [comment]
Hi, the easiest way to achieve this currently is probably to track the current month. Then each time you click the previous/next button increment your increment/decrement your counter. Create a new date instance by adding the counter to the month of a java Calendar object and call ```setCurrentDate(Date dateTimeMonth) ``` on the compact calendar instance, this will set the date on the calendar to the one passed in and will update the calendar to the correct month. This is a bit of an inconvenience :(.

There is no easy way to achieve this since the calendar doesn't expose such functionality in the api, for example like showNextMonth/showPreviousMonth. Is this something you would like? If you want I can add this functionality sometime this week.

Thanks.

**Comment by javo0112** [comment]
well it ended being not that inconvenient, since i am using JodaTime in my app, what i did based on your recommendation, is use getFirstDayOfCurrentMonth(); to obtain a date and later with joda time i added one month and set it.

```java
 public void onClick(View v) {

                Date fechaActual = compactCalendarView.getFirstDayOfCurrentMonth();
                DateTime fechaA = new DateTime(fechaActual);

                compactCalendarView.setCurrentDate(fechaA.plusMonths(1).toDate());
            }
```

although it would be nice to have a method to do that in one line. 

thanks for the support.

**Comment by SundeepK** [comment]
No problem, I will add some methods that will allow for this functionality some time later this week. So watch this ticket to keep up to date so that you know when to update to the latest.

**Comment by SundeepK** [comment]
Will need to release changes. Will update ticket once that's done.

**Comment by SundeepK** [comment]
Available in 

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.1'
}
```

**Comment by javo0112** [comment]
Thank you, SundeepK
