### ISSUE TITLE
How can i change current day to surrounded circle instead of background color

### ISSUE THREAD

**Issue by nAkhmedov** [SundeepK/CompactCalendarView#80]
Hi there! Thank you for awesome lib! I need to change current day view to rounded circle with white border instead of bg color. How can i do it.Thanks in advance
![default](https://cloud.githubusercontent.com/assets/8067423/16070427/b5a7c1be-32ee-11e6-88da-e88ad01e165a.png)

**Comment by SundeepK** [comment]
Hi, this is easily achieved by using `setStyle(Paint.Style.STROKE);`. Currently, however, there is no method in api todo so. As you can see below, there is a draw method for drawing circles, for both small and large indicators:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L884

You will need to account for only large indicators, so extra logic is required when a small indicator is being drawn because you may not want that to be a filled circle. 

Small indicators are drawn using this method:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L878

You can modify the parameters in the method to take a boolean and have a check. So, you can take a fork of the code and import it as a module and make the appropriate changes. It's a bit ugly since the method has too many parameters in my opinion but you can make changes to suit your needs. 

I'm not sure when I will be able todo this within the library, but atleast you have an idea on how to do this in the mean time.

**Comment by nAkhmedov** [comment]
Thanks for your response

**Comment by nAkhmedov** [comment]
One more thing how can i set another color for custom dates like compactCalendarCurrentDayBackgroundColor?

**Comment by nAkhmedov** [comment]
i want to set custom bg color for several dates

**Comment by robbyl** [comment]
I also want the same thing, want to achieve something like this
![preview](https://cloud.githubusercontent.com/assets/1931548/16117645/c61c5c38-33db-11e6-8773-5d366e323752.jpg) Custom background color like that of first day of the month or current date for specified date

**Comment by nAkhmedov** [comment]
@robbyl  Could you share these code?

**Comment by SundeepK** [comment]
I was having a think about this, I think there are 2 ways to go about doing this:

1. We can have an xml property which says `compactCalendarIndicatorStyle="fill_large_indicator"` and `compactCalendarCurrentDayStyle=no_fill_large_indicator` where possible styles can be `fill_large_indicator`, `no_fill_large_indicator`, `small_indicator`. It will default to `small_indicator` since that is probably what most people what to achieve the google calendar look.
2. Embed in the style in the actual `Event` class. I'm leaning towards more for the styled approach, which might be easier to implement.

What are your thoughts?

**Comment by robbyl** [comment]
That will be nice

**Comment by robbyl** [comment]
Was able to fill color on event by setting compactCalendarView.drawSmallIndicatorForEvents(false);

**Comment by SundeepK** [comment]
@robbyl What version are you using? I removed that functionality a while ago because I wanted it to follow the Google calendar view. Obviously people need that functionality, so I will be adding it back soon. I would also suggest you update to the latest since it has more improvements as well.

**Comment by SundeepK** [comment]
Having a look at this now, will update once I have something done. I think releasing a beta might be a good choice so that people can give inputs/thoughts.

**Comment by SundeepK** [comment]
Hi all, below are some example screenshots what is now possible. You should be able to customise the indicators as follows:

![large-filled-ind](https://cloud.githubusercontent.com/assets/2339563/17925467/0435303c-69e5-11e6-86de-c578dff8a60c.png)
![no-fill-ind](https://cloud.githubusercontent.com/assets/2339563/17925470/0444bf66-69e5-11e6-8bf6-e40cd8bfa4dd.png)
![normal-ind](https://cloud.githubusercontent.com/assets/2339563/17925469/043b0340-69e5-11e6-8695-42eb07e5a5dc.png)
![small-event-ind](https://cloud.githubusercontent.com/assets/2339563/17925468/043b2a0a-69e5-11e6-9ed8-c8dcd6de97a4.png)

Is anyone interested in doing some testing? I tend to release beta test versions so that people can try things out and report back with feedback. This generally gets rid of the pain of the wrong things being implemented and a nice way to give feedback.

Note: the screenshots are slightly low quality since I had to resize them.

**Comment by SundeepK** [comment]
Just an update, I'm currently adding support for screenshot-tests-for-android to make testing easier with screenshots and ensure nothing breaks between releases. I'm almost done with this so expect something soon.

**Comment by XxGoliathusxX** [comment]
compile version?

**Comment by SundeepK** [comment]
Below is a beta version, I've tested this on android 7 as there was a bug that caused an issue in the new version (now is fixed). Also tested on an emulator for pre android 7. Should be downloadable soon, thanks!

```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.1-beta-1.0'
}
```

**Comment by XxGoliathusxX** [comment]
How does it work?
 app:compactCalendarCurrentDayIndicatorStyle="fill_large_indicator"
                    app:compactCalendarCurrentSelectedDayIndicatorStyle="fill_large_indicator"
                    app:compactCalendarEventIndicatorStyle="small_indicator"
Draws a cycle around a eventday. But no indicators are drawn anymore!

**Comment by SundeepK** [comment]
@XxGoliathusxX can you share your layout XML please?

**Comment by XxGoliathusxX** [comment]
<com.github.sundeepk.compactcalendarview.CompactCalendarView
                    android:layout_below="@+id/header"
                    xmlns:app="http://schemas.android.com/apk/res-auto"
                    android:id="@+id/compactcalendar_view"
                    android:layout_width="fill_parent"
                    android:layout_height="250dp"
                    android:layout_marginBottom="8dp"
                    app:compactCalendarTextSize="14sp"
                    app:compactCalendarBackgroundColor="@color/primary_light"
                    app:compactCalendarTextColor="@color/white"
                    app:compactCalendarCurrentSelectedDayBackgroundColor="@color/primary"
                    app:compactCalendarCurrentDayBackgroundColor="@color/accent"
                    app:compactCalendarMultiEventIndicatorColor="@color/white"
app:compactCalendarCurrentDayIndicatorStyle="fill_large_indicator"
app:compactCalendarCurrentSelectedDayIndicatorStyle="fill_large_indicator"
app:compactCalendarEventIndicatorStyle="small_indicator"
                    />

**Comment by SundeepK** [comment]
Interesting, I have tried this on an emulator, Samsung galaxy S4 and nexus 6p (android 7) and it all seems to work as expected using the sample app (in branch @enhancement/#80_customize_indicators). Perhaps there's something different in your setup code?

With the xml you showed, it display small dots for events and a solid filled circle for the current day and the currently selected day by the user.

**Comment by XxGoliathusxX** [comment]
Ok after reinstalling the app it works. But what's it for? When I set the select-day indicator to be not filled and I click on it, i cant see the event-indicators. Moreover if I click on the current day it does not change its color. Also there I cant see the event-indicators. There is no advantage in this update!!!

**Comment by SundeepK** [comment]
Thanks! Yes there no functional change its much more for customise look and feel. However, this version has fixes to work with new android 7.0 as well so its has some features. Remember, you don't have to use these extra xml properties as it will default to the normal google calendar look and feel.

**Comment by XxGoliathusxX** [comment]
But how can I get the event-indicators in front of the the day-indicator?

**Comment by SundeepK** [comment]
Not supported yet, but I'll look into this issue as priority for next release!

**Comment by SundeepK** [comment]
Avaible in:
```gradle

dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.1'
}

```

**Comment by robbyl** [comment]
This is awesome

**Comment by loigiepanganoron** [comment]
hi guys , im using this CompactCalendarView , i have a question how to achieve like [this](https://i.stack.imgur.com/H7Wlr.png) .. thanks guys..

@SundeepK @robbyl @bearprada @XxGoliathusxX @nAkhmedov

**Comment by rohitpanhalkar001** [comment]
> Hi all, below are some example screenshots what is now possible. You should be able to customise the indicators as follows:
> 
> ![large-filled-ind](https://cloud.githubusercontent.com/assets/2339563/17925467/0435303c-69e5-11e6-86de-c578dff8a60c.png)
> ![no-fill-ind](https://cloud.githubusercontent.com/assets/2339563/17925470/0444bf66-69e5-11e6-8bf6-e40cd8bfa4dd.png)
> ![normal-ind](https://cloud.githubusercontent.com/assets/2339563/17925469/043b0340-69e5-11e6-8695-42eb07e5a5dc.png)
> ![small-event-ind](https://cloud.githubusercontent.com/assets/2339563/17925468/043b2a0a-69e5-11e6-9ed8-c8dcd6de97a4.png)
> 
> Is anyone interested in doing some testing? I tend to release beta test versions so that people can try things out and report back with feedback. This generally gets rid of the pain of the wrong things being implemented and a nice way to give feedback.
> 
> Note: the screenshots are slightly low quality since I had to resize them and you can still select different colors for different events. I just used one color for the example but I can have different colors.

Can you please share the code for adding a background circle indicator color to multiple dates.
